# .github/workflows/python-package.yml
name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:   # Added permissions
      contents: read
      id-token: write  # Required for OIDC with Trusted Publishing

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Build the package  # Added step to build the distribution
      run: |
        pip install build
        python -m build
    - name: Publish to PyPI
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://upload.pypi.org/legacy/
